'use strict'

const _ = require('lodash')
const logger = require('winston')
const mailer = require('gmail-send')({
  user: 'gnywedding@gmail.com',
  pass: 'oczsmmygcspphbjv'
})

exports.send = async function(data) {

  logger.info(`mailer.js: Email Requested for ${JSON.stringify(data)}`)

  await mailer({
    to: ['gnywedding@gmail.com', 'ustgian25@gmail.com', 'alyssa.denaya@gmail.com'],
    subject: `Wedding RSVP Submitted - ${data.name}`,
    html: '<p>An RSVP has been submitted from https://gnywedding2019.herokuapp.com with the following details:</p>' +
      '<ul>' +
      `<li><b>Name:</b> ${data.name}</li>` +
      `<li><b>Email:</b> ${data.email}</li>` +
      `<li><b>Phone:</b> ${data.phone}</li>` +
      '</ul><br><br>' +
      '<p style="color: #FF0000;">This is an autogenerated email</p>'
  }, function(err, res) {
    logger.info(`mailer.js: ${JSON.stringify(res)}`)
    if(!_.isNil(err)) {
      logger.error(`mailer.js: ${JSON.stringify(err)}`)
    }
  })
}
